config/routes.rb
Rails.application.routes.draw do
  resources :users
  get 'signup', to: 'users#new'

  resources :sessions
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :events, only: [:new, :create, :show, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: "User"

  has_many :event_attendings, foreign_key: :attended_event_id
  has_many :event_attendees, through: :event_attendings, source: :event_attendee

  scope :past, -> { where('DATE(date) <= ?', Date.today) }
  scope :today, -> { where('DATE(date) = ? ', Date.today) }
  scope :upcoming, -> { where('DATE(date) > ?', Date.today) }

end

app/models/event_attending.rb
class EventAttending < ApplicationRecord
  belongs_to :event_attendee, class_name: "User"
  belongs_to :attended_event, class_name: "Event"
end

app/models/user.rb
class User < ApplicationRecord
  has_many :created_events, foreign_key: "creator_id", class_name: "Event"

  has_many :event_attendings, foreign_key: :event_attendee_id
  has_many :attended_events, through: :event_attendings

  def upcoming_events
    filtered_events = []
    self.event_attendings.each do |event|
      if  Event.find(event.attended_event_id).date > Date.today
        filtered_events << Event.find(event.attended_event_id)
      end
    end
    filtered_events
  end

  def prev_events
    filtered_events = []
    self.event_attendings.each do |event|
      if Event.find(event.attended_event_id).date < Date.today
        filtered_events << Event.find(event.attended_event_id)
      end
    end
    filtered_events
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def new
    @event = Event.new
  end

  def create
    @event = current_user.created_events.build(created_events_params)
    if @event.save
      flash[:success] = "Event saved!"
      redirect_to current_user
    else
      render 'new'
    end
  end

  def show
    @event = Event.find(params[:id])
    @event_attendees = @event.event_attendees.all
  end

  def index
    @events = Event.all
    @past = Event.past
    @today = Event.today
    @upcoming = Event.upcoming
  end

  private

    def created_events_params
      params.require(:event).permit(:name, :date, :description)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(username: params[:session][:username])
    if user 
      log_in user
      redirect_to user
    else
      flash.now[:danger] = "Username does not exist"
      render 'new'
    end
  end

  def destroy
    log_out
    flash[:success] = "You are logged out"
    redirect_to login_path
  end
end
 

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to Elvents!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @created_events = @user.created_events
    @attended_events = @user.attended_events.all
    @upcoming_events = @user.upcoming_events
    @prev_events = @user.prev_events
  end

  private

    def user_params
      params.require(:user).permit(:username)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
  include SessionsHelper

  def full_title(page_title = "")
    base_title = "Elvents"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
  
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id 
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<%= provide(:title, "Events") %>
<h1>All Events</h1>

<% unless @today.empty? %> 
  <h3>Today's Events: <%= @today.count %></h3>
  <ul>
    <% @today.each do |event| %>
      <li><a href="/events/<%= event.id %>"><%= event.description%></a> 
      by <a href="/users/<%= event.creator.id %>"><%= event.creator.username %></a></li>
    <% end %>
  </ul>
<% else %>
  <h3>There are no events today</h3>
<% end %>

<% unless @past.empty? %> 
  <h3>Passed Events: <%= @past.count %></h3>
  <ul>
    <% @past.each do |event| %>
      <li><a href="/events/<%= event.id %>"><%= event.description%></a> 
      by <a href="/users/<%= event.creator.id %>"><%= event.creator.username %></a></li>
    <% end %>
  </ul>
<% else %>
  <h3>There are no passed events</h3>
<% end %>

<% unless @upcoming.empty? %>
  <h3>Upcoming Events: <%= @upcoming.count %></h3>
  <ul>
    <% @upcoming.each do |event| %>
      <li><a href="/events/<%= event.id %>"><%= event.description%></a> 
      by <a href="/users/<%= event.creator.id %>"><%= event.creator.username %></a></li>
    <% end %>
  </ul>
<% else %>
  <h3>There are no upcoming events</h3>
<% end %>

app/views/events/new.html.erb
<%= provide(:title, "Create event") %>
<h1>Create Event</h1>

<%= form_with(model: @event, local:true) do |f| %>

  <%= f.label :description %>
  <%= f.text_field :description %><br></br>

  <%= f.label :date %>
  <%= f.date_field :date %><br></br>

  <%= f.submit "Create event"%>

<% end %>

app/views/events/show.html.erb
<%= provide(:title, @event.description) %>
<h1><%= @event.description %></h1>

Event created by <a href="/users/<%= @event.creator.id %>">
                  <%= @event.creator.username %></a><br>
<% if !@event.date.nil? %>
  Date: <%= @event.date %>
<% else %>
  Date is TBA
<% end %>

<br></br>Attendees: 
<% @event_attendees.each do |attendee| %>
  <li><a href="/users/<%= attendee.id %>"><%= attendee.username %></a></li>
<% end %>

app/views/layouts/_header.html.erb
<% if logged_in? %>
  <strong><%= current_user.username %></strong> is logged in<br>
  <%= link_to "Create event", new_event_path %>
  <%= link_to "My events", user_path(current_user.id) %>
  <%= link_to "Show events", events_path %>
  <%= link_to "Log out", logout_path, method: :delete %><br></br>
<% else %>
  <%= link_to "Login", login_path %>
  <%= link_to "Sign up", signup_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div>
      <% flash.each do |message_type, message| %>
        <%= message %>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<%= provide(:title, "Signup")%>
<h1>New user</h1>
<%= form_with(model: @user, local: true) do |f| %>

  <%= f.label :username %>
  <%= f.text_field :username%>

  <%= f.submit "Create account" %>

<% end %>

app/views/users/show.html.erb
<%= provide(:title, @user.username) %>

<%= @user.username%><br></br>

<% if @user.created_events.any? %>
  Created events: <%= @user.created_events.count %>
  <ol>
    <% @created_events.each do |event| %>
      <li><a href="/events/<%= event.id %>"><%= event.description %></a></li>
    <% end %>
  </ol>
<% else %>
  <%= @user.username %> has no created events.
<% end %>
<br></br>

<% if @user.attended_events.any? %>
  Attended events: <%= @user.attended_events.count %>
  <% @attended_events.each do |event| %>
    <li><a href="/events/<%= event.id %>"><%= event.description %></a></li>
  <% end %>
<% else %>

<% end %>